version: '3'

services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: book
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./migration/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - book-network
networks:
  book-network:
    driver: bridge